# Makefile automatically generated by ghdl
# Version: GHDL 5.1.1 (tarball) [Dunoon edition] - static elaboration, mcode JIT code generator
# Command used to generate this makefile:
# ghdl gen-makefile --std=08 riscvdriver

GHDL=ghdl
GHDLFLAGS= --std=08
GHDLRUNFLAGS=

# Default target : elaborate
all : elab

# Elaborate target.  Almost useless
elab : force
	$(GHDL) -c $(GHDLFLAGS) -e riscvdriver

# Run target
run : force
	$(GHDL) -c $(GHDLFLAGS) -r riscvdriver $(GHDLRUNFLAGS)

# Targets to analyze libraries
init: force
	# /usr/lib/ghdl/std/v08/../../src/std/v08/textio.vhdl
	# /usr/lib/ghdl/std/v08/../../src/std/v08/textio-body.vhdl
	# /usr/lib/ghdl/ieee/v08/../../src/ieee2008/std_logic_1164.vhdl
	# /usr/lib/ghdl/ieee/v08/../../src/ieee2008/std_logic_1164-body.vhdl
	# /usr/lib/ghdl/ieee/v08/../../src/ieee2008/numeric_std.vhdl
	# /usr/lib/ghdl/ieee/v08/../../src/ieee2008/numeric_std-body.vhdl
	$(GHDL) -a $(GHDLFLAGS) ./src/riscv.vhdl
	$(GHDL) -a $(GHDLFLAGS) ./src/riscv_driver.vhdl

force:
